# Generated by Django 6.0.5 on 2026-05-20 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='season.chapter')),
                ('draga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='season.dragaseasonendata')),
            ],
        ),
    ]
