# Generated by Django 6.0.5 on 2026-05-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DragaSeasonenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='draga.feminosa')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='season.season')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='season.season')),
            ],
        ),
    ]
