# Generated by Django 6.0.5 on 2026-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
