# Generated by Django 6.0.5 on 2026-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragaseasonendata',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
